server:
  port: 8081
spring:
  application:
    name: peekgo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/peekgo?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    virtual-host: /
    port: 5672
    username: guest
    password: guest
    host: 127.0.0.1
mybatis-plus:
  type-aliases-package: com.peekgo.entity # 别名扫描包
logging:
  level:
    com.peekgo: debug